controllers/bagunis.py
from flask import *
from db import mysql
from parselib import parseCafe24Mall

bagunis = Blueprint('bagunis', __name__, template_folder='templates')

@bagunis.route('/main/<user>/bagunis/<int:baguniid>', methods=['GET', 'POST'])
def bagunis_route(user, baguniid):
	# Check if a user is logged in
	# If not, redirect to the main page for login
	if 'email' not in session:
		print 'Not logged in: redirecting to main...'
		return redirect(url_for('main.main_route'))

	# Check if the url is the right url for the current user
	session_username = session['email'].split('@')[0]
	if session_username != user:
		return render_template('403.html'), 403

	# Check if the current Baguni is displayed to the right user
	curBaguniid = baguniid

	query_getEmail = 'SELECT email FROM BaguniAccess WHERE baguniid = %s'
	data_getEmail = [curBaguniid]

	conn = mysql.get_db()
	cursor = conn.cursor()
	cursor.execute(query_getEmail, data_getEmail)

	try:
		db_email = cursor.fetchall()[0][0]
		if db_email != session['email']:
			return render_template('403.html'), 403
	except IndexError:
		return render_template('403.html'), 403


	if request.method == 'GET':
		# Get info about items in the current Baguni from the database
		query_getItems = 'SELECT * FROM Item WHERE baguniid = %s ORDER BY itemname ASC'
		data_getItems = [curBaguniid]

		conn = mysql.get_db()
		cursor = conn.cursor()
		cursor.execute(query_getItems, data_getItems)
		db_items = cursor.fetchall()

		items = []
		checked = ''
		for db_item in db_items:
			if db_item[7] == 1:
				checked = 'checked'

			item = {
				'origurl': db_item[2],
				'imageurl': db_item[3],
				'price': db_item[4],
				'brand': db_item[5],
				'name': db_item[6],
				'selected': checked
			}
			items.append(item)

		return render_template("bagunis.html", items = items)
	if request.method == 'POST':
		# Receive json object from ajax request
		jsondata = request.get_json()
		itemURL = jsondata['itemURL']
		curStep = jsondata['step']

		print curStep

		if curStep == 0:
			# Parse the url given
			parseResult = parseCafe24Mall(itemURL)
			# {
			# 	'domain': domain,
			# 	'img': img,
			# 	'name': name,
			# 	'price': price,
			# 	'info': info
			# }

			parseSuccess = parseResult[0]
			parseError = parseResult[1]
			parseInfo = parseResult[2]
			print parseError
			print parseInfo
			
			return jsonify(
				errorMessage = parseError,
				checkImage = parseInfo['img'],
				checkBrand = parseInfo['domain'],
				checkName = parseInfo['name'],
				checkPrice = parseInfo['price'],
				moreInfo = parseInfo['info']
			)
		elif curStep == 1:
			print jsondata['price']
			print jsondata['moreInfo']
			query_addItem = ('INSERT INTO Item(baguniid, originalurl, imageurl, price, '
							 'brandname, itemname, addInfo) VALUES (%s,%s,%s,%s,%s,%s,%s)')
			data_addItem = [baguniid, itemURL, jsondata['imageURL'], jsondata['price'], jsondata['brandName'],
							jsondata['itemName'], jsondata['moreInfo']]

			conn = mysql.get_db()
			cursor = conn.cursor()
			cursor.execute(query_addItem, data_addItem)
			conn.commit()

		return ('', 200)

controllers/login.py
from flask import *
from db import mysql
import encrypt

login = Blueprint('login', __name__, template_folder='templates')

@login.route('/login', methods=['GET', 'POST'])
def login_route():
	if request.method == 'GET':
		return render_template('login.html')
	elif request.method == 'POST':
		f = request.form

		query_GetUser = 'SELECT * FROM User WHERE email = %s'
		data_GetUser = [f['email']]
		
		conn = mysql.get_db()
		cursor = conn.cursor()
		cursor.execute(query_GetUser, data_GetUser)
		result = cursor.fetchall()
		error = ''

		# If a user does not exist
		if not result:
			error = 'Email does not exist'
		# If password does not match
		else:
			# Get the existing salt
			dbSalt = result[0][2].split('$')[1]
			dbPassword = result[0][2]

			formPassword = encrypt.encryptPassword(dbSalt, f['password'])
			
			if formPassword != dbPassword:
				error = 'Wrong password'
			else:
				# on Success, create a session, include username as a part of url
				session['email'] = f['email']
				session['name'] = result[0][0] + ' ' + result[0][1]
				user = f['email'].split('@')[0]
				session['user'] = user
				return redirect(url_for('main_user.main_user_route', user=session['user']))
		
		return render_template('login.html', error = error)

controllers/main.py
from flask import *
from db import mysql

main = Blueprint('main', __name__, template_folder = 'templates')

@main.route('/main')
def main_route():
	return render_template('main.html')



main_user = Blueprint('main_user', __name__, template_folder='templates')

@main_user.route('/main/<user>', methods=['GET', 'POST'])
def main_user_route(user):
	# Check if a user is logged in
	# If not, redirect to the main page for login
	if 'email' not in session:
		print 'Not logged in: redirecting to main...'
		return redirect(url_for('main.main_route'))

	# Check if the url is the right url for the current user 
	if session['user'] != user:
		return render_template('403.html'), 403

	if request.method == 'GET':
		print 'baguni GET'
		# Get all the Baguni IDs associated with the email account
		query_getBaguniId = 'SELECT * FROM BaguniAccess WHERE email = %s'
		data_getBaguniId = [session['email']]

		conn = mysql.get_db()
		cursor = conn.cursor()
		cursor.execute(query_getBaguniId, data_getBaguniId)
		baguniid = cursor.fetchall()

		bagunis = []

		for i in range(0, len(baguniid)):
			curBaguniId = baguniid[i][1]
			# For each Baguni ID, get Baguni info
			query_getBaguni = 'SELECT * FROM Baguni WHERE baguniid = %s'
			data_getBaguni = [curBaguniId]

			cursor.execute(query_getBaguni, data_getBaguni)
			baguni = cursor.fetchall()[0]

			# For each Baguni, count the number of items in that Baguni
			query_getNumItems = 'SELECT COUNT(itemid) FROM Item WHERE baguniid = %s'
			data_getNumItems = [curBaguniId]

			cursor.execute(query_getNumItems, data_getNumItems)
			numItems = cursor.fetchall()[0][0]

			# For each Baguni, count the number of items SELECTED in that Baguni
			query_getNumSelected = 'SELECT COUNT(itemid) FROM Item WHERE baguniid = %s AND selected = %s'
			data_getNumSelected = [curBaguniId, 1]

			cursor.execute(query_getNumSelected, data_getNumSelected)
			numSelected = cursor.fetchall()[0][0]


			newBaguni = [baguni, numItems, numSelected]
			
			bagunis.append(newBaguni)

		return render_template("main_user.html", bagunis = bagunis, user = user)

	if request.method == 'POST':
		print 'baguni POST'
		jsondata = request.get_json()
		baguniName = jsondata['baguniName']
		baguniColor = jsondata['baguniColor']

		# Insert into Baguni
		query_addBaguni = 'INSERT INTO Baguni (email, title, color) VALUES (%s, %s, %s)'
		data_addBaguni = [session['email'], baguniName, baguniColor]

		conn = mysql.get_db()
		cursor = conn.cursor()
		cursor.execute(query_addBaguni, data_addBaguni)
		conn.commit()

		# Get the id of inserted Baguni
		query_getBaguniId = 'SELECT LAST_INSERT_ID()'
		
		baguniid = cursor.execute(query_getBaguniId)
		baguniid = cursor.fetchall()[0]

		# Insert into BaguniAccess the newly added Baguni
		query_addBagAccess = 'INSERT INTO BaguniAccess (email, baguniid) VALUES (%s, %s)'
		data_addBagAccess = [session['email'], baguniid]

		cursor.execute(query_addBagAccess, data_addBagAccess)
		conn.commit()

		return ('', 200)


# api_addBaguni = Blueprint('api_addBaguni', __name__)

# @api_addBaguni.route('/api/v1/addBaguni', methods=['POST'])
# def api_addBaguni_route():
# 	if request.method == 'POST':
# 		print 'baguni POST'
# 		jsondata = request.get_json()
# 		baguniName = jsondata['baguniName']
# 		baguniColor = jsondata['baguniColor']

# 		# Insert into Baguni
# 		query_addBaguni = 'INSERT INTO Baguni (email, title, color) VALUES (%s, %s, %s)'
# 		data_addBaguni = [session['email'], baguniName, baguniColor]

# 		conn = mysql.get_db()
# 		cursor = conn.cursor()
# 		cursor.execute(query_addBaguni, data_addBaguni)
# 		conn.commit()

# 		# Get the id of inserted Baguni
# 		query_getBaguniId = 'SELECT LAST_INSERT_ID()'
		
# 		baguniid = cursor.execute(query_getBaguniId)
# 		baguniid = cursor.fetchall()[0]

# 		# Insert into BaguniAccess the newly added Baguni
# 		query_addBagAccess = 'INSERT INTO BaguniAccess (email, baguniid) VALUES (%s, %s)'
# 		data_addBagAccess = [session['email'], baguniid]

# 		cursor.execute(query_addBagAccess, data_addBagAccess)
# 		conn.commit()

# 		return ('', 200)
# 		# return render_template("baguni.html")

controllers/signup.py
from flask import *
from db import mysql
import encrypt

signup = Blueprint('signup', __name__, template_folder='templates')

@signup.route('/signup', methods=['GET', 'POST'])
def signup_route():
	if request.method == 'GET':
		print 'SignUp GET'
		return render_template('signup.html')

	elif request.method == 'POST':
		print 'SignUp POST'

		f = request.form

		# Create a new User
		if checkIfEmailExists(f['email']):
			salt = encrypt.genSalt()
			newPassword = encrypt.encryptPassword(salt, f['password'])

			query_AddUser = 'INSERT INTO User VALUES (%s,%s,%s,%s,%s)'
			data_AddUser = [f['firstname'], f['lastname'], newPassword, f['email'], f['phone']]
			
			conn = mysql.get_db()
			cursor = conn.cursor()
			cursor.execute(query_AddUser, data_AddUser)
			conn.commit()

			# on Success, create a session, include username as a part of url
			session['email'] = f['email']
			session['name'] = f['firstname'] + ' ' + f['lastname']
			user = f['email'].split('@')[0]
			session['user'] = user
			return redirect(url_for('main_user.main_user_route', user=session['user']))
		else:
			error = 'Email already exists'
			return render_template('signup.html', error = error)

# Function to check if provided email already exists in the db
def checkIfEmailExists(email):
	print 'checkIfEmailExists'
	query_GetEmail = 'SELECT * FROM User WHERE email = %s'
	data_GetEmail = [email]

	conn = mysql.get_db()
	cursor = conn.cursor()
	cursor.execute(query_GetEmail, data_GetEmail)
	result = cursor.fetchall()
	print len(result)
	if len(result) == 0:
		return True
	return False

templates/bags_inside.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Baguni</title>

	<link rel="stylesheet" href="src/css/reset.css">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<link rel="stylesheet" href="src/css/style.css">

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
	<!-- NAVIGATION BAR -->
	<div class="container-fluid">
		<div class="row">
			<nav class="nav-all nav-upper navbar-fixed-top">
				<a class="align-left" href="#"><span class="icon icon-search"></span></a>
				<span class="icon icon-logo"></span>
				<a href="" class="align-right"><span class="icon icon-settings"></span></a>
			</nav>
		</div>
	</div>
	
	<ul class="bags-inside">
		<li class="active"><a href="#">One</a></li><!-- 
		 --><li class="inactive"><a href="#">Two</a></li><!-- 
		 --><li class="inactive"><a href="#">Three</a></li><!-- 
		 --><li class="inactive"><a href="#">Four</a></li><!-- 
		 --><li class="inactive"><a href="#">Five</a></li>
	</ul>

	<div class="container-fluid">
		<div class="row">
			<nav class="nav-all nav-mid">
				<div class="price-bar align-left">$ <span></span></div>
				<a href="#"><span class="icon-md icon-refine"></span></a>
				<a href="#"><span class="icon-md icon-sort"></span></a>
			</nav>
		</div>
	</div>
	
	<!-- SECOND PAGE -->
	<div class="container">
		<ul class="items">
			<li class="col-xs-6 item" id="product_id">
				<input type="checkbox" name="item" class="item-checkbox">
				<ul class="item-detail">
					<li class="item-qty">Qty: <span></span></li>
					<li class="item-size">Size: <span></span></li>
				</ul>
				<div class="row">
					<a href="#"><img src="src/img/sample/sweater.png" alt="" class="item-image"></a>
				</div>
				<div class="row">
					<ul>
						<li class="item-brand">Google</li>
						<li class="item-name">Firebase</li>
					</ul>
				</div>
				<div class="row">
					<p class="item-price">$<span id="item-price"></span></p>
					<img src="src/img/icons/logo/logo_amazon.png" alt="" class="item-brand-logo">
				</div>

			</li>
		</ul>
	</div>

	<!-- NAVIGATION BAR -->
	<div class="container-fluid">
		<div class="row">
			<nav class="nav-all nav-lower navbar-fixed-bottom">
				<ul>
					<li class="nav-item"><a href="#"><span class="icon-md icon-folders"></span></a></li>
					<li class="nav-item"><a href="#"><span class="icon-md icon-blink"></span></a></li>
					<li class="nav-item"><a href="#"><span class="icon-lg icon-purchase"></span></a></li>
					<li class="nav-item"><a href="#"><span class="icon-md icon-explore"></span></a></li>
					<li class="nav-item"><a href="#"><span class="icon-md icon-more"></span></a></li>
					<span class="stretch"></span>
				</ul>
			</nav>
		</div>
	</div>
</body>
</html>

templates/bagunis.html
{% extends "base_navBar.html" %}
{% block content %}
	<!-- Modal for adding new item -->
	<div class="modal fade" id="modal-add-item">
		<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Add an item!</h4>
			</div>
			<div class="modal-body">
				<h5>Paste the URL of the item to be added:</h5>
				<input type="text" name="modal-input-url" id="modal-input-url">
				<div class="modal-body-nested">
					<h5>Is this the item you were looking at?</h5>
					<img src="" alt="">
					<dl class="dl-horizontal">
						<dt>From</dt>
						<dd></dd>
						<dt>Item</dt>
						<dd></dd>
						<dt>Price</dt>
						<dd></dd>
					</dl>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-black" id="modal-btn-add">Parse</button>
				<button class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
	</div>

	<ul class="baguni-tab">
		<li class="active"><a href="#">One</a></li><!-- 
		 --><li class="inactive"><a href="#">Two</a></li><!-- 
		 --><li class="inactive"><a href="#">Three</a></li><!-- 
		 --><li class="inactive"><a href="#">Four</a></li><!-- 
		 --><li class="inactive"><a href="#">Five</a></li>
	</ul>

	<div class="container-fluid">
		<div class="row">
			<nav class="nav-all nav-mid">
				<div class="price-bar align-left">$ <span></span></div>
				<a href="#"><span class="icon-md icon-refine"></span></a>
				<a href="#"><span class="icon-md icon-sort"></span></a>
			</nav>
		</div>
	</div>
	
	<div class="container container-items">
		<ul class="items">
			{% for item in items %}
				<li class="col-xs-6 item" id="product_id">
					<div class="row">
					<input type="checkbox" name="item" class="item-checkbox" {{ item['selected'] }}></div>
					<!-- <ul class="item-detail">
						<li class="item-qty">Qty: <span></span></li>
						<li class="item-size">Size: <span></span></li>
					</ul> -->
					<div class="row">
						<a href="{{ item['origurl'] }}"><img src="{{ item['imageurl'] }}" alt="" class="item-image"></a>
					</div>
					<div class="row">
						<h5 class="item-brand">쇼핑몰:&nbsp;</h5><p>{{ item['brand'] }}</p>
						<h5 class="item-name">상품명:&nbsp;</h5><p>{{ item['name'] }}</p>
					</div>
					<div class="row">
						<h5 class="item-price">가격(원): &nbsp;</h5><p id="item-price">{{ item['price'] }}</p>
					</div>
				</li>
			{% endfor %}
		</ul>
	</div>

	<button class="btn-add-black" data-toggle="modal" data-target="#modal-add-item"><span class="glyphicon glyphicon-plus"></span></button>
	
	<script src="{{url_for('static', filename='js/bagunis.js')}}"></script>
{% endblock %}

templates/base_noNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Baguni</title>

	<link rel="stylesheet" href="{{url_for('static', filename='css/reset.css')}}">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base_noNavBar.html" %}
{% block content %}
	<div class="container div-main">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
			<h3 class="intro-text"><strong>THE ONLY SHOPPING BAG YOU WILL EVER NEED.</strong></h3>	
			
			<div class="btn-main">
				<a href="{{url_for('signup.signup_route')}}" role="button">SIGN UP</a>	
				<a href="{{url_for('login.login_route')}}" role="button">LOG IN</a>
			</div>
		</div>
		</div>
		<div class="col-xs-2"></div>
	</div>
{% endblock%}

templates/login.html
{% extends "base_noNavBar.html" %}
{% block content %}
	<div class="container">
		<form action="{{url_for('login.login_route')}}" method='POST' class="form-login">
			<div class="col-xs-2"></div>
			<div class="col-xs-8">
				<h3><strong>Welcome Back!</strong></h3>
				<div class="form-group">
					<label for="input-login-email" class="control-label">Email</label>	
					<input type="text" placeholder="Email@email.com" name="email" id="input-login-email" class="form-control">
				</div>
				<div class="form-group">
					<label for="input-login-password" class="control-label">Password</label>
					<input type="password" placeholder="Password" name="password" id="input-login-password" class="form-control">
				</div>
				{% if error %}
					<p class="error-msg">{{error}}</p>
				{% endif %}
				<button type="submit" class="btn btn-black" id="btn-login">Login</button>
			</div>
			<div class="col-xs-2"></div>
		</form>
	</div>
{% endblock %}

templates/main.html
{% extends "base_noNavBar.html" %}
{% block content %}
	<div class="container div-main">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
			<h3 class="intro-text"><strong>THE ONLY SHOPPING BAG YOU WILL EVER NEED.</strong></h3>	
			
			<div class="btn-main">
				<a href="{{url_for('signup.signup_route')}}" role="button">SIGN UP</a>	
				<a href="{{url_for('login.login_route')}}" role="button">LOG IN</a>
			</div>
		</div>
		</div>
		<div class="col-xs-2"></div>
	</div>
{% endblock%}

templates/main_user.html
{% extends "base_navBar.html"%}
{% block content %}
	<div class="modal fade" id="modal-add-baguni">
		<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header"><h4>Add a Baguni!</h4></div>
			<div class="modal-body">
				<h5>Name of the new Baguni:</h5>
					<input type="text" name="baguni-name" id="input-baguni-name">
				<h5>Choose the color of the new Baguni:</h5>
				<div class="radio">
					<label for="input-baguni-green">
						<input type="radio" name="baguni-color" id="input-baguni-green" value="green">
						<span class="baguni-mini baguni-green"></span>
					</label>
					<label for="input-baguni-red">
						<input type="radio" name="baguni-color" id="input-baguni-red" value="red">
						<span class="baguni-mini baguni-red"></span>
					</label>
					<label for="input-baguni-yellow">
						<input type="radio" name="baguni-color" id="input-baguni-yellow" value="yellow">
						<span class="baguni-mini baguni-yellow"></span>
					</label>
					<label for="input-baguni-purple">
						<input type="radio" name="baguni-color" id="input-baguni-purple" value="purple">
						<span class="baguni-mini baguni-purple"></span>
					</label>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" id="btn-add-baguni" data-dismiss="modal">Add</button>
				<button class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
	</div>

	<!-- FIRST PAGE -->
	<div class="bg"></div>

	<div class="container-fluid">
		<div class="row">
			<nav class="nav-all nav-mid">
				<button class="btn-add align-left" data-toggle="modal" data-target="#modal-add-baguni"><span class="glyphicon glyphicon-plus"></span></button>
				<a href="#"><span class="icon-md icon-refine"></span></a>
				<a href="#"><span class="icon-md icon-sort"></span></a>
			</nav>
		</div>
	</div>

	<div class="container container-bagunis">
		{% for baguni in bagunis %}
		<a href="{{url_for('bagunis.bagunis_route', user=user, baguniid=baguni[0][1])}}">
			<div class="col-xs-6">
				<div class="baguni baguni-{{ baguni[0][3]}}">
					<h5 class="baguni-title">{{baguni[0][2]}}</h5>
					<div class="baguni-info">
						<p class="baguni-numItems"><span>{{baguni[1]}}</span> items</p>
						<p class="baguni-numSelected"><span>{{baguni[2]}}</span> selected</p>
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
	<script src="{{url_for('static', filename='js/main.js')}}"></script>
{% endblock %}

templates/signup.html
{% extends "base_noNavBar.html" %}
{% block content %}
	<div class="container">
		<form action="{{url_for('signup.signup_route')}}" method="POST" class="form-signup" id="form-signup">
			<div class="col-xs-2"></div>
			<div class="col-xs-8">
				<h3><strong>Hello!</strong></h3>
				<div class="form-group">
					<label for="input-signup-firstname" class="control-label">Firstname</label>
					<input type="text" placeholder="Firstname" name="firstname" id="input-signup-firstname" class="form-control">
					<span class="help-block"></span>
				</div>
				<div class="form-group">
					<label for="input-signup-lastname" class="control-label">Lastname</label>
					<input type="text" placeholder="Lastname" name="lastname" id="input-signup-lastname" class="form-control">
					<span class="help-block"></span>
				</div>
				<div class="form-group">
					<label for="input-signup-email" class="control-label">Email</label>
					<input type="email" placeholder="email@email.com" name="email" id="input-signup-email" class="form-control">
					<span class="help-block"></span>
				</div>
				<div class="form-group">
					<label for="input-signup-password" class="control-label">Password</label>
					<input type="password" placeholder="Password" name="password" id="input-signup-password" class="form-control">
					<span class="help-block"></span>
				</div>
				<div class="form-group">
					<label for="input-signup-phone" class="control-label">Phone Number</label>
					<input type="tel" placeholder="xxx-xxx-xxxx" name="phone" id="input-signup-phone" class="form-control">
					<span class="help-block"></span>
				</div>
				{% if error %}
					<p class="error-msg">{{error}}</p>
				{% endif %}
				<button type="submit" class="btn btn-black">Sign Me Up!</button>
			</div>
			<div class="col-xs-2"></div>
		</form>
	</div>
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
	<script src="{{url_for('static', filename='js/signup.js')}}"></script>
{% endblock %}